language: node_js
cache:
  npm: false
script:
- npm run test
- npm run lint
before_install:
- openssl aes-256-cbc -K $encrypted_c589161bbc05_key -iv $encrypted_c589161bbc05_iv
  -in .env.test.enc -out .env.test -d
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
